service: customers

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-2
  environment:
    CUSTOMERS_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CUSTOMERS_TABLE}"
      
plugins:
  - serverless-offline
  
functions:
  createCustomer:
    handler: customers/create.create
    events:
      - http:
          path: customers
          method: post
          cors: true
  listCustomer:
    handler: customers/list.list
    events:
      - http:
          path: customers
          method: get
          cors: true

  getCustomer:
    handler: customers/get.get
    events:
      - http:
          path: customers/{id}
          method: get
          cors: true

  updateCustomer:
    handler: customers/update.update
    events:
      - http:
          path: customers/{id}
          method: put
          cors: true

  deleteCustomer:
    handler: customers/delete.delete
    events:
      - http:
          path: customers/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CUSTOMERS_TABLE}
