// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-2:fd1d66ac-825c-492a-903b-c49f344673e7',
    'aws_cognito_region': 'eu-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'esurelogin-hosting-mobilehub-1214971760',
    'aws_content_delivery_bucket_region': 'eu-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3gl307vgsohan.cloudfront.net',
    'aws_mobile_analytics_app_id': '96f2c42a3fb442419e3b1075b12beea8',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'f1352dcd-ef3a-4c24-8a34-78aed32d1adf',
    'aws_project_name': 'esure-login',
    'aws_project_region': 'eu-west-2',
    'aws_resource_name_prefix': 'esurelogin-mobilehub-1214971760',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-2_JTCxVPEYs',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '1fru533tngp37vvi9fnc5e004',
}

export default awsmobile;
